// src/constants/mapData.ts
import { PoliticalCategory } from "../types/map";

export const stateAbbreviations: { [key: string]: string } = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};

export const statePolitics: { [key: string]: PoliticalCategory } = {
  California: "solid-dem",
  Maryland: "solid-dem",
  Massachusetts: "solid-dem",
  "New York": "solid-dem",
  Oregon: "solid-dem",
  Delaware: "solid-dem",
  Connecticut: "solid-dem",
  "New Jersey": "solid-dem",
  "New Mexico": "solid-dem",
  Illinois: "solid-dem",
  Washington: "solid-dem",
  Hawaii: "solid-dem",
  Maine: "solid-dem",
  Vermont: "solid-dem",
  "Rhode Island": "solid-dem",

  // Lean Democratic (mírně více DEM registrací)
  Colorado: "lean-dem",
  Nevada: "lean-dem",
  Virginia: "lean-dem",
  Minnesota: "lean-dem",
  "New Hampshire": "lean-dem",

  // Swing States (velmi vyrovnané registrace)
  Pennsylvania: "swing",
  Florida: "swing",
  Michigan: "swing",
  Arizona: "swing",
  Georgia: "swing",
  "North Carolina": "swing",
  Wisconsin: "swing",

  // Lean Republican (mírně více REP registrací)
  Texas: "lean-rep",
  Ohio: "lean-rep",
  Iowa: "lean-rep",
  Montana: "lean-rep",

  // Solid Republican (významně více REP registrací)
  Alabama: "solid-rep",
  Alaska: "solid-rep",
  Arkansas: "solid-rep",
  Idaho: "solid-rep",
  Indiana: "solid-rep",
  Kansas: "solid-rep",
  Kentucky: "solid-rep",
  Louisiana: "solid-rep",
  Mississippi: "solid-rep",
  Missouri: "solid-rep",
  Nebraska: "solid-rep",
  "North Dakota": "solid-rep",
  Oklahoma: "solid-rep",
  "South Carolina": "solid-rep",
  "South Dakota": "solid-rep",
  Tennessee: "solid-rep",
  Utah: "solid-rep",
  "West Virginia": "solid-rep",
  Wyoming: "solid-rep",
};
